// Code generated by MockGen. DO NOT EDIT.
package web

import (
	"context"
	"reflect"

	"github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	"go.uber.org/mock/gomock"
)

// MockTransactionUseCase is a mock of application.TransactionUseCase interface.
type MockTransactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUseCaseMockRecorder
}

// MockTransactionUseCaseMockRecorder is the mock recorder for MockTransactionUseCase.
type MockTransactionUseCaseMockRecorder struct {
	mock *MockTransactionUseCase
}

func NewMockTransactionUseCase(ctrl *gomock.Controller) *MockTransactionUseCase {
	mock := &MockTransactionUseCase{ctrl: ctrl}
	mock.recorder = &MockTransactionUseCaseMockRecorder{mock}
	return mock
}

func (m *MockTransactionUseCase) EXPECT() *MockTransactionUseCaseMockRecorder {
	return m.recorder
}

func (m *MockTransactionUseCase) Create(arg0 context.Context, arg1 models.TransactionModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTransactionUseCaseMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionUseCase)(nil).Create), arg0, arg1)
}

func (m *MockTransactionUseCase) GetTransactionIdsOfUser(arg0 context.Context, arg1 models.UserModel) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionIdsOfUser", arg0, arg1)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTransactionUseCaseMockRecorder) GetTransactionIdsOfUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionIdsOfUser", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionIdsOfUser), arg0, arg1)
}

func (m *MockTransactionUseCase) Update(arg0 context.Context, arg1 models.TransactionModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockTransactionUseCaseMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTransactionUseCase)(nil).Update), arg0, arg1)
}

func (m *MockTransactionUseCase) Delete(arg0 context.Context, arg1, arg2 int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTransactionUseCaseMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTransactionUseCase)(nil).Delete), arg0, arg1, arg2)
}

func (m *MockTransactionUseCase) Detail(arg0 context.Context, arg1, arg2 int) (models.TransactionModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.TransactionModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTransactionUseCaseMockRecorder) Detail(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTransactionUseCase)(nil).Detail), arg0, arg1, arg2)
}

func (m *MockTransactionUseCase) IsUserAuthorOfTransaction(arg0 models.UserModel, arg1 models.TransactionModel) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfTransaction", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (mr *MockTransactionUseCaseMockRecorder) IsUserAuthorOfTransaction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).IsUserAuthorOfTransaction), arg0, arg1)
}

// MockEnumsUseCase is a mock of application.EnumsUseCase interface.
type MockEnumsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEnumsUseCaseMockRecorder
}

type MockEnumsUseCaseMockRecorder struct {
	mock *MockEnumsUseCase
}

func NewMockEnumsUseCase(ctrl *gomock.Controller) *MockEnumsUseCase {
	mock := &MockEnumsUseCase{ctrl: ctrl}
	mock.recorder = &MockEnumsUseCaseMockRecorder{mock}
	return mock
}

func (m *MockEnumsUseCase) EXPECT() *MockEnumsUseCaseMockRecorder { return m.recorder }

func (m *MockEnumsUseCase) GetCurrencyCodes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyCodes")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (mr *MockEnumsUseCaseMockRecorder) GetCurrencyCodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyCodes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetCurrencyCodes))
}

func (m *MockEnumsUseCase) GetTransactionTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (mr *MockEnumsUseCaseMockRecorder) GetTransactionTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionTypes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetTransactionTypes))
}

func (m *MockEnumsUseCase) GetCategoryTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (mr *MockEnumsUseCaseMockRecorder) GetCategoryTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTypes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetCategoryTypes))
}

// MockAccountUseCase is a mock of application.AccountUseCase interface.
type MockAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUseCaseMockRecorder
}

type MockAccountUseCaseMockRecorder struct {
	mock *MockAccountUseCase
}

func NewMockAccountUseCase(ctrl *gomock.Controller) *MockAccountUseCase {
	mock := &MockAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUseCaseMockRecorder{mock}
	return mock
}

func (m *MockAccountUseCase) EXPECT() *MockAccountUseCaseMockRecorder { return m.recorder }

func (m *MockAccountUseCase) Create(arg0 context.Context, arg1 models.AccountModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountUseCaseMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountUseCase)(nil).Create), arg0, arg1)
}

func (m *MockAccountUseCase) LinkAccountAndUser(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAccountAndUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockAccountUseCaseMockRecorder) LinkAccountAndUser(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAccountAndUser", reflect.TypeOf((*MockAccountUseCase)(nil).LinkAccountAndUser), arg0, arg1, arg2)
}

func (m *MockAccountUseCase) IsUserAuthorOfAccount(arg0 context.Context, arg1, arg2 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (mr *MockAccountUseCaseMockRecorder) IsUserAuthorOfAccount(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfAccount", reflect.TypeOf((*MockAccountUseCase)(nil).IsUserAuthorOfAccount), arg0, arg1, arg2)
}

func (m *MockAccountUseCase) GetAccountIdByUserId(arg0 context.Context, arg1 int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIdByUserId", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAccountUseCaseMockRecorder) GetAccountIdByUserId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdByUserId", reflect.TypeOf((*MockAccountUseCase)(nil).GetAccountIdByUserId), arg0, arg1)
}
