// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ai/ai.go

// Package aimocks is a generated GoMock package.
package aimocks

import (
	context "context"
	reflect "reflect"

	groq "github.com/go-park-mail-ru/2026_1_GPTeam/internal/ai/groq"
	gomock "github.com/golang/mock/gomock"
)

// MockAiService is a mock of AiService interface.
type MockAiService struct {
	ctrl     *gomock.Controller
	recorder *MockAiServiceMockRecorder
}

// MockAiServiceMockRecorder is the mock recorder for MockAiService.
type MockAiServiceMockRecorder struct {
	mock *MockAiService
}

// NewMockAiService creates a new mock instance.
func NewMockAiService(ctrl *gomock.Controller) *MockAiService {
	mock := &MockAiService{ctrl: ctrl}
	mock.recorder = &MockAiServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAiService) EXPECT() *MockAiServiceMockRecorder {
	return m.recorder
}

// ParseTransaction mocks base method.
func (m *MockAiService) ParseTransaction(ctx context.Context, transcript string, types, categories []string) (*groq.TransactionDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTransaction", ctx, transcript, types, categories)
	ret0, _ := ret[0].(*groq.TransactionDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTransaction indicates an expected call of ParseTransaction.
func (mr *MockAiServiceMockRecorder) ParseTransaction(ctx, transcript, types, categories interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTransaction", reflect.TypeOf((*MockAiService)(nil).ParseTransaction), ctx, transcript, types, categories)
}

// Transcribe mocks base method.
func (m *MockAiService) Transcribe(ctx context.Context, audioData []byte, filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, audioData, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockAiServiceMockRecorder) Transcribe(ctx, audioData, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockAiService)(nil).Transcribe), ctx, audioData, filename)
}
