// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/auth.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthenticationService is a mock of AuthenticationService interface.
type MockAuthenticationService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationServiceMockRecorder
}

// MockAuthenticationServiceMockRecorder is the mock recorder for MockAuthenticationService.
type MockAuthenticationServiceMockRecorder struct {
	mock *MockAuthenticationService
}

// NewMockAuthenticationService creates a new mock instance.
func NewMockAuthenticationService(ctrl *gomock.Controller) *MockAuthenticationService {
	mock := &MockAuthenticationService{ctrl: ctrl}
	mock.recorder = &MockAuthenticationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationService) EXPECT() *MockAuthenticationServiceMockRecorder {
	return m.recorder
}

// ClearOld mocks base method.
func (m *MockAuthenticationService) ClearOld(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearOld", ctx, w, r)
}

// ClearOld indicates an expected call of ClearOld.
func (mr *MockAuthenticationServiceMockRecorder) ClearOld(ctx, w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearOld", reflect.TypeOf((*MockAuthenticationService)(nil).ClearOld), ctx, w, r)
}

// GenerateNewAuth mocks base method.
func (m *MockAuthenticationService) GenerateNewAuth(ctx context.Context, w http.ResponseWriter, userId int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GenerateNewAuth", ctx, w, userId)
}

// GenerateNewAuth indicates an expected call of GenerateNewAuth.
func (mr *MockAuthenticationServiceMockRecorder) GenerateNewAuth(ctx, w, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNewAuth", reflect.TypeOf((*MockAuthenticationService)(nil).GenerateNewAuth), ctx, w, userId)
}

// IsAuth mocks base method.
func (m *MockAuthenticationService) IsAuth(ctx context.Context, r *http.Request) (bool, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuth", ctx, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// IsAuth indicates an expected call of IsAuth.
func (mr *MockAuthenticationServiceMockRecorder) IsAuth(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuth", reflect.TypeOf((*MockAuthenticationService)(nil).IsAuth), ctx, r)
}

// Refresh mocks base method.
func (m *MockAuthenticationService) Refresh(ctx context.Context, w http.ResponseWriter, r *http.Request) (bool, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, w, r)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthenticationServiceMockRecorder) Refresh(ctx, w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthenticationService)(nil).Refresh), ctx, w, r)
}
