listen_addresses = '*'
max_connections = 150
superuser_reserved_connections = 3

tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 5

log_destination = 'stderr'
logging_collector = on
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_file_mode = 0640
log_rotation_age = 1d
log_rotation_size = 0
log_truncate_on_rotation = on
log_connections = on
log_disconnections = on
log_min_duration_statement = 400
log_duration = off
log_lock_waits = on
log_line_prefix = '%t [%p]: user=%u,db=%d,client=%h '
log_checkpoints = on
log_timezone = 'Europe/Moscow'

shared_buffers = 256MB
effective_cache_size = 1GB
work_mem = 8MB
maintenance_work_mem = 64MB

checkpoint_timeout = 15min

password_encryption = scram-sha-256
ssl = off

shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = 'all'
