listen_addresses = '*'
max_connections = 150
superuser_reserved_connections = 3

tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 5

log_connections = on
log_disconnections = on
log_min_duration_statement = 1000
log_line_prefix = '%t [%p]: user=%u,db=%d,client=%h'

shared_buffers = 256MB
effective_cache_size = 1GB
work_mem = 8MB
maintenance_work_mem = 64MB

checkpoint_timeout = 15min

password_encryption = scram-sha-256
ssl = off
