// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -source=jwt.go -destination=mocks/jwt.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtRepository is a mock of JwtRepository interface.
type MockJwtRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJwtRepositoryMockRecorder
	isgomock struct{}
}

// MockJwtRepositoryMockRecorder is the mock recorder for MockJwtRepository.
type MockJwtRepositoryMockRecorder struct {
	mock *MockJwtRepository
}

// NewMockJwtRepository creates a new mock instance.
func NewMockJwtRepository(ctrl *gomock.Controller) *MockJwtRepository {
	mock := &MockJwtRepository{ctrl: ctrl}
	mock.recorder = &MockJwtRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtRepository) EXPECT() *MockJwtRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJwtRepository) Create(ctx context.Context, token models.RefreshTokenModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJwtRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJwtRepository)(nil).Create), ctx, token)
}

// DeleteByUserId mocks base method.
func (m *MockJwtRepository) DeleteByUserId(ctx context.Context, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserId", ctx, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserId indicates an expected call of DeleteByUserId.
func (mr *MockJwtRepositoryMockRecorder) DeleteByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserId", reflect.TypeOf((*MockJwtRepository)(nil).DeleteByUserId), ctx, userId)
}

// DeleteByUuid mocks base method.
func (m *MockJwtRepository) DeleteByUuid(ctx context.Context, uuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUuid", ctx, uuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUuid indicates an expected call of DeleteByUuid.
func (mr *MockJwtRepositoryMockRecorder) DeleteByUuid(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUuid", reflect.TypeOf((*MockJwtRepository)(nil).DeleteByUuid), ctx, uuid)
}

// Get mocks base method.
func (m *MockJwtRepository) Get(ctx context.Context, uuid string) (models.RefreshTokenModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, uuid)
	ret0, _ := ret[0].(models.RefreshTokenModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJwtRepositoryMockRecorder) Get(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJwtRepository)(nil).Get), ctx, uuid)
}
