// Code generated by MockGen. DO NOT EDIT.
// Source: support.go
//
// Generated by this command:
//
//	mockgen -source=support.go -destination=mocks/mock_support.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSupportRepository is a mock of SupportRepository interface.
type MockSupportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSupportRepositoryMockRecorder
	isgomock struct{}
}

// MockSupportRepositoryMockRecorder is the mock recorder for MockSupportRepository.
type MockSupportRepositoryMockRecorder struct {
	mock *MockSupportRepository
}

// NewMockSupportRepository creates a new mock instance.
func NewMockSupportRepository(ctrl *gomock.Controller) *MockSupportRepository {
	mock := &MockSupportRepository{ctrl: ctrl}
	mock.recorder = &MockSupportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportRepository) EXPECT() *MockSupportRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSupportRepository) Create(ctx context.Context, model models.SupportModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, model)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSupportRepositoryMockRecorder) Create(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSupportRepository)(nil).Create), ctx, model)
}

// GetAll mocks base method.
func (m *MockSupportRepository) GetAll(ctx context.Context) ([]models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSupportRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSupportRepository)(nil).GetAll), ctx)
}

// GetAllByUser mocks base method.
func (m *MockSupportRepository) GetAllByUser(ctx context.Context, userId int) ([]models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, userId)
	ret0, _ := ret[0].([]models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockSupportRepositoryMockRecorder) GetAllByUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockSupportRepository)(nil).GetAllByUser), ctx, userId)
}

// GetById mocks base method.
func (m *MockSupportRepository) GetById(ctx context.Context, id int) (models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockSupportRepositoryMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockSupportRepository)(nil).GetById), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockSupportRepository) UpdateStatus(ctx context.Context, id int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSupportRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSupportRepository)(nil).UpdateStatus), ctx, id, status)
}
