// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/account.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountRepository) Create(ctx context.Context, account models.AccountModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountRepositoryMockRecorder) Create(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountRepository)(nil).Create), ctx, account)
}

// GetAccountIdByUserId mocks base method.
func (m *MockAccountRepository) GetAccountIdByUserId(ctx context.Context, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIdByUserId", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdByUserId indicates an expected call of GetAccountIdByUserId.
func (mr *MockAccountRepositoryMockRecorder) GetAccountIdByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdByUserId", reflect.TypeOf((*MockAccountRepository)(nil).GetAccountIdByUserId), ctx, userId)
}

// GetAllAccountsByUserId mocks base method.
func (m *MockAccountRepository) GetAllAccountsByUserId(ctx context.Context, userId int) ([]models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountsByUserId", ctx, userId)
	ret0, _ := ret[0].([]models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountsByUserId indicates an expected call of GetAllAccountsByUserId.
func (mr *MockAccountRepositoryMockRecorder) GetAllAccountsByUserId(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountsByUserId", reflect.TypeOf((*MockAccountRepository)(nil).GetAllAccountsByUserId), ctx, userId)
}

// GetAllAccountsByUserIdWithBalance mocks base method.
func (m *MockAccountRepository) GetAllAccountsByUserIdWithBalance(ctx context.Context, userId int) ([]models.AccountModel, []float64, []float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountsByUserIdWithBalance", ctx, userId)
	ret0, _ := ret[0].([]models.AccountModel)
	ret1, _ := ret[1].([]float64)
	ret2, _ := ret[2].([]float64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllAccountsByUserIdWithBalance indicates an expected call of GetAllAccountsByUserIdWithBalance.
func (mr *MockAccountRepositoryMockRecorder) GetAllAccountsByUserIdWithBalance(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountsByUserIdWithBalance", reflect.TypeOf((*MockAccountRepository)(nil).GetAllAccountsByUserIdWithBalance), ctx, userId)
}

// GetCurrencyByAccountId mocks base method.
func (m *MockAccountRepository) GetCurrencyByAccountId(ctx context.Context, accountId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyByAccountId", ctx, accountId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencyByAccountId indicates an expected call of GetCurrencyByAccountId.
func (mr *MockAccountRepositoryMockRecorder) GetCurrencyByAccountId(ctx, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyByAccountId", reflect.TypeOf((*MockAccountRepository)(nil).GetCurrencyByAccountId), ctx, accountId)
}

// GetIdsByUserAndAccount mocks base method.
func (m *MockAccountRepository) GetIdsByUserAndAccount(ctx context.Context, userId, accountId int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdsByUserAndAccount", ctx, userId, accountId)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdsByUserAndAccount indicates an expected call of GetIdsByUserAndAccount.
func (mr *MockAccountRepositoryMockRecorder) GetIdsByUserAndAccount(ctx, userId, accountId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdsByUserAndAccount", reflect.TypeOf((*MockAccountRepository)(nil).GetIdsByUserAndAccount), ctx, userId, accountId)
}

// LinkAccountAndUser mocks base method.
func (m *MockAccountRepository) LinkAccountAndUser(ctx context.Context, accountId, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAccountAndUser", ctx, accountId, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkAccountAndUser indicates an expected call of LinkAccountAndUser.
func (mr *MockAccountRepositoryMockRecorder) LinkAccountAndUser(ctx, accountId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAccountAndUser", reflect.TypeOf((*MockAccountRepository)(nil).LinkAccountAndUser), ctx, accountId, userId)
}
