// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/enums.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEnumsRepository is a mock of EnumsRepository interface.
type MockEnumsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnumsRepositoryMockRecorder
}

// MockEnumsRepositoryMockRecorder is the mock recorder for MockEnumsRepository.
type MockEnumsRepositoryMockRecorder struct {
	mock *MockEnumsRepository
}

// NewMockEnumsRepository creates a new mock instance.
func NewMockEnumsRepository(ctrl *gomock.Controller) *MockEnumsRepository {
	mock := &MockEnumsRepository{ctrl: ctrl}
	mock.recorder = &MockEnumsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnumsRepository) EXPECT() *MockEnumsRepositoryMockRecorder {
	return m.recorder
}

// GetCategoryTypesFromDB mocks base method.
func (m *MockEnumsRepository) GetCategoryTypesFromDB() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTypesFromDB")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetCategoryTypesFromDB indicates an expected call of GetCategoryTypesFromDB.
func (mr *MockEnumsRepositoryMockRecorder) GetCategoryTypesFromDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTypesFromDB", reflect.TypeOf((*MockEnumsRepository)(nil).GetCategoryTypesFromDB))
}

// GetCurrencyCodesFromDB mocks base method.
func (m *MockEnumsRepository) GetCurrencyCodesFromDB() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyCodesFromDB")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetCurrencyCodesFromDB indicates an expected call of GetCurrencyCodesFromDB.
func (mr *MockEnumsRepositoryMockRecorder) GetCurrencyCodesFromDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyCodesFromDB", reflect.TypeOf((*MockEnumsRepository)(nil).GetCurrencyCodesFromDB))
}

// GetTransactionTypesFromDB mocks base method.
func (m *MockEnumsRepository) GetTransactionTypesFromDB() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionTypesFromDB")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetTransactionTypesFromDB indicates an expected call of GetTransactionTypesFromDB.
func (mr *MockEnumsRepositoryMockRecorder) GetTransactionTypesFromDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionTypesFromDB", reflect.TypeOf((*MockEnumsRepository)(nil).GetTransactionTypesFromDB))
}
