// Code generated by MockGen. DO NOT EDIT.
// Source: budget.go
//
// Generated by this command:
//
//	mockgen -source=budget.go -destination=mocks/mock_budget.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetRepository is a mock of BudgetRepository interface.
type MockBudgetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetRepositoryMockRecorder
	isgomock struct{}
}

// MockBudgetRepositoryMockRecorder is the mock recorder for MockBudgetRepository.
type MockBudgetRepositoryMockRecorder struct {
	mock *MockBudgetRepository
}

// NewMockBudgetRepository creates a new mock instance.
func NewMockBudgetRepository(ctrl *gomock.Controller) *MockBudgetRepository {
	mock := &MockBudgetRepository{ctrl: ctrl}
	mock.recorder = &MockBudgetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetRepository) EXPECT() *MockBudgetRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBudgetRepository) Create(ctx context.Context, budget models.BudgetModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, budget)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBudgetRepositoryMockRecorder) Create(ctx, budget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBudgetRepository)(nil).Create), ctx, budget)
}

// Delete mocks base method.
func (m *MockBudgetRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBudgetRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBudgetRepository)(nil).Delete), ctx, id)
}

// GetById mocks base method.
func (m *MockBudgetRepository) GetById(ctx context.Context, id int) (models.BudgetModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(models.BudgetModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBudgetRepositoryMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBudgetRepository)(nil).GetById), ctx, id)
}

// GetCategoryOfBudget mocks base method.
func (m *MockBudgetRepository) GetCategoryOfBudget(ctx context.Context, id int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryOfBudget", ctx, id)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryOfBudget indicates an expected call of GetCategoryOfBudget.
func (mr *MockBudgetRepositoryMockRecorder) GetCategoryOfBudget(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryOfBudget", reflect.TypeOf((*MockBudgetRepository)(nil).GetCategoryOfBudget), ctx, id)
}

// GetIdsByUserId mocks base method.
func (m *MockBudgetRepository) GetIdsByUserId(ctx context.Context, userId int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdsByUserId", ctx, userId)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdsByUserId indicates an expected call of GetIdsByUserId.
func (mr *MockBudgetRepositoryMockRecorder) GetIdsByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdsByUserId", reflect.TypeOf((*MockBudgetRepository)(nil).GetIdsByUserId), ctx, userId)
}

// LinkBudgetAndCategory mocks base method.
func (m *MockBudgetRepository) LinkBudgetAndCategory(ctx context.Context, budgetId int, category string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkBudgetAndCategory", ctx, budgetId, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkBudgetAndCategory indicates an expected call of LinkBudgetAndCategory.
func (mr *MockBudgetRepositoryMockRecorder) LinkBudgetAndCategory(ctx, budgetId, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkBudgetAndCategory", reflect.TypeOf((*MockBudgetRepository)(nil).LinkBudgetAndCategory), ctx, budgetId, category)
}
