// Code generated by MockGen. DO NOT EDIT.
// Source: rate_limiter.go
//
// Generated by this command:
//
//	mockgen -source=rate_limiter.go -destination=mocks/rate_limiter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBucketInterface is a mock of BucketInterface interface.
type MockBucketInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBucketInterfaceMockRecorder
	isgomock struct{}
}

// MockBucketInterfaceMockRecorder is the mock recorder for MockBucketInterface.
type MockBucketInterfaceMockRecorder struct {
	mock *MockBucketInterface
}

// NewMockBucketInterface creates a new mock instance.
func NewMockBucketInterface(ctrl *gomock.Controller) *MockBucketInterface {
	mock := &MockBucketInterface{ctrl: ctrl}
	mock.recorder = &MockBucketInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBucketInterface) EXPECT() *MockBucketInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBucketInterface) Get(ctx context.Context, ip string) (models.BucketModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, ip)
	ret0, _ := ret[0].(models.BucketModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBucketInterfaceMockRecorder) Get(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBucketInterface)(nil).Get), ctx, ip)
}

// GetPermanentBlocked mocks base method.
func (m *MockBucketInterface) GetPermanentBlocked(ctx context.Context) (models.PermanentBlockedIps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermanentBlocked", ctx)
	ret0, _ := ret[0].(models.PermanentBlockedIps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermanentBlocked indicates an expected call of GetPermanentBlocked.
func (mr *MockBucketInterfaceMockRecorder) GetPermanentBlocked(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermanentBlocked", reflect.TypeOf((*MockBucketInterface)(nil).GetPermanentBlocked), ctx)
}

// Save mocks base method.
func (m *MockBucketInterface) Save(ctx context.Context, ip string, bucket models.BucketModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, ip, bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockBucketInterfaceMockRecorder) Save(ctx, ip, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockBucketInterface)(nil).Save), ctx, ip, bucket)
}

// SetPermanentBlocked mocks base method.
func (m *MockBucketInterface) SetPermanentBlocked(ctx context.Context, ips models.PermanentBlockedIps) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermanentBlocked", ctx, ips)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermanentBlocked indicates an expected call of SetPermanentBlocked.
func (mr *MockBucketInterfaceMockRecorder) SetPermanentBlocked(ctx, ips any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermanentBlocked", reflect.TypeOf((*MockBucketInterface)(nil).SetPermanentBlocked), ctx, ips)
}
