// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *UserSearchResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in UserSearchResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserSearchResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserSearchResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserSearchResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserSearchResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(in *jlexer.Lexer, out *PendingInviteView) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "account_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountName = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(out *jwriter.Writer, in PendingInviteView) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"account_name\":"
		out.RawString(prefix)
		out.String(string(in.AccountName))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PendingInviteView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PendingInviteView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PendingInviteView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PendingInviteView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(in *jlexer.Lexer, out *MemberResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "is_owner":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOwner = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(out *jwriter.Writer, in MemberResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"is_owner\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsOwner))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MemberResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MemberResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MemberResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MemberResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(in *jlexer.Lexer, out *InviteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Users":
			if in.IsNull() {
				in.Skip()
				out.Users = nil
			} else {
				in.Delim('[')
				if out.Users == nil {
					if !in.IsDelim(']') {
						out.Users = make([]UserSearchResult, 0, 1)
					} else {
						out.Users = []UserSearchResult{}
					}
				} else {
					out.Users = (out.Users)[:0]
				}
				for !in.IsDelim(']') {
					var v1 UserSearchResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Users = append(out.Users, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(out *jwriter.Writer, in InviteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Users\":"
		out.RawString(prefix[1:])
		if in.Users == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Users {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InviteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InviteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InviteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InviteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(in *jlexer.Lexer, out *InviteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "query":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Query = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(out *jwriter.Writer, in InviteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"query\":"
		out.RawString(prefix[1:])
		out.String(string(in.Query))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InviteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InviteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InviteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InviteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(in *jlexer.Lexer, out *AccountUserUpdateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Status = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(out *jwriter.Writer, in AccountUserUpdateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix[1:])
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserUpdateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserUpdateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserUpdateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserUpdateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(in *jlexer.Lexer, out *AccountUserModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(out *jwriter.Writer, in AccountUserModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(l, v)
}
func easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(in *jlexer.Lexer, out *AccountUserCreateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "AccountId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(out *jwriter.Writer, in AccountUserCreateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"AccountId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserCreateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserCreateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9ea7856dEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserCreateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserCreateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9ea7856dDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(l, v)
}
