// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *AccountUpdateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
				out.Balance = nil
			} else {
				if out.Balance == nil {
					out.Balance = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Balance = float64(in.Float64())
				}
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
				out.Currency = nil
			} else {
				if out.Currency == nil {
					out.Currency = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Currency = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in AccountUpdateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		if in.Balance == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.Balance))
		}
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		if in.Currency == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Currency))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUpdateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUpdateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUpdateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUpdateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
func easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(in *jlexer.Lexer, out *AccountModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = float64(in.Float64())
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "OwnerId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerId = int(in.Int())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(out *jwriter.Writer, in AccountModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Float64(float64(in.Balance))
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"OwnerId\":"
		out.RawString(prefix)
		out.Int(int(in.OwnerId))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(l, v)
}
func easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(in *jlexer.Lexer, out *AccountCreateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = float64(in.Float64())
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "OwnerId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerId = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(out *jwriter.Writer, in AccountCreateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Float64(float64(in.Balance))
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"OwnerId\":"
		out.RawString(prefix)
		out.Int(int(in.OwnerId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountCreateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountCreateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson349b126bEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountCreateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountCreateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson349b126bDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(l, v)
}
