// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson171edd05DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *RefreshTokenModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uuid = string(in.String())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "ExpiredAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ExpiredAt).UnmarshalJSON(data))
				}
			}
		case "DeviceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson171edd05EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in RefreshTokenModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Uuid))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"ExpiredAt\":"
		out.RawString(prefix)
		out.Raw((in.ExpiredAt).MarshalJSON())
	}
	{
		const prefix string = ",\"DeviceId\":"
		out.RawString(prefix)
		out.String(string(in.DeviceId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RefreshTokenModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson171edd05EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RefreshTokenModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson171edd05EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RefreshTokenModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson171edd05DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RefreshTokenModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson171edd05DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
