// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *UserSearchResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in UserSearchResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserSearchResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserSearchResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserSearchResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserSearchResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(in *jlexer.Lexer, out *UserModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "Username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Password = string(in.String())
			}
		case "Email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "LastLogin":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastLogin).UnmarshalJSON(data))
				}
			}
		case "AvatarUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AvatarUrl = string(in.String())
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "Active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Active = bool(in.Bool())
			}
		case "IsStaff":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsStaff = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(out *jwriter.Writer, in UserModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"Username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	{
		const prefix string = ",\"Email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"LastLogin\":"
		out.RawString(prefix)
		out.Raw((in.LastLogin).MarshalJSON())
	}
	{
		const prefix string = ",\"AvatarUrl\":"
		out.RawString(prefix)
		out.String(string(in.AvatarUrl))
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"Active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	{
		const prefix string = ",\"IsStaff\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsStaff))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(in *jlexer.Lexer, out *UpdateUserProfile) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "Username":
			if in.IsNull() {
				in.Skip()
				out.Username = nil
			} else {
				if out.Username == nil {
					out.Username = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Username = string(in.String())
				}
			}
		case "Email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Email = string(in.String())
				}
			}
		case "Password":
			if in.IsNull() {
				in.Skip()
				out.Password = nil
			} else {
				if out.Password == nil {
					out.Password = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Password = string(in.String())
				}
			}
		case "AvatarUrl":
			if in.IsNull() {
				in.Skip()
				out.AvatarUrl = nil
			} else {
				if out.AvatarUrl == nil {
					out.AvatarUrl = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.AvatarUrl = string(in.String())
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(out *jwriter.Writer, in UpdateUserProfile) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"Username\":"
		out.RawString(prefix)
		if in.Username == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Username))
		}
	}
	{
		const prefix string = ",\"Email\":"
		out.RawString(prefix)
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"Password\":"
		out.RawString(prefix)
		if in.Password == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Password))
		}
	}
	{
		const prefix string = ",\"AvatarUrl\":"
		out.RawString(prefix)
		if in.AvatarUrl == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AvatarUrl))
		}
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateUserProfile) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateUserProfile) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateUserProfile) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateUserProfile) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels2(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(in *jlexer.Lexer, out *TransactionModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "AccountId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "Value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "Type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "Category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "TransactionDate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TransactionDate).UnmarshalJSON(data))
				}
			}
		case "DeletedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.DeletedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(out *jwriter.Writer, in TransactionModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"AccountId\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"Category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"TransactionDate\":"
		out.RawString(prefix)
		out.Raw((in.TransactionDate).MarshalJSON())
	}
	{
		const prefix string = ",\"DeletedAt\":"
		out.RawString(prefix)
		out.Raw((in.DeletedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TransactionModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TransactionModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TransactionModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TransactionModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels3(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(in *jlexer.Lexer, out *TransactionDraft) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "raw_text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawText = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "recorded_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.RecordedAt).UnmarshalJSON(data))
				}
			}
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Date).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(out *jwriter.Writer, in TransactionDraft) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"raw_text\":"
		out.RawString(prefix[1:])
		out.String(string(in.RawText))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"recorded_at\":"
		out.RawString(prefix)
		out.Raw((in.RecordedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.Raw((in.Date).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TransactionDraft) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TransactionDraft) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TransactionDraft) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TransactionDraft) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels4(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(in *jlexer.Lexer, out *SupportModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "Category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "Message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "Deleted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Deleted = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(out *jwriter.Writer, in SupportModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"Category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"Message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"Deleted\":"
		out.RawString(prefix)
		out.Bool(bool(in.Deleted))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SupportModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SupportModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SupportModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SupportModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels5(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(in *jlexer.Lexer, out *RefreshTokenModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Uuid = string(in.String())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "ExpiredAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.ExpiredAt).UnmarshalJSON(data))
				}
			}
		case "DeviceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceId = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(out *jwriter.Writer, in RefreshTokenModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Uuid))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"ExpiredAt\":"
		out.RawString(prefix)
		out.Raw((in.ExpiredAt).MarshalJSON())
	}
	{
		const prefix string = ",\"DeviceId\":"
		out.RawString(prefix)
		out.String(string(in.DeviceId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RefreshTokenModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RefreshTokenModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RefreshTokenModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RefreshTokenModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels6(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(in *jlexer.Lexer, out *PermanentBlockedIps) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Ips":
			if in.IsNull() {
				in.Skip()
				out.Ips = nil
			} else {
				in.Delim('[')
				if out.Ips == nil {
					if !in.IsDelim(']') {
						out.Ips = make([]string, 0, 4)
					} else {
						out.Ips = []string{}
					}
				} else {
					out.Ips = (out.Ips)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Ips = append(out.Ips, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(out *jwriter.Writer, in PermanentBlockedIps) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Ips\":"
		out.RawString(prefix[1:])
		if in.Ips == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Ips {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PermanentBlockedIps) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PermanentBlockedIps) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PermanentBlockedIps) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PermanentBlockedIps) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels7(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(in *jlexer.Lexer, out *PendingInviteView) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "account_name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountName = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(out *jwriter.Writer, in PendingInviteView) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"account_name\":"
		out.RawString(prefix)
		out.String(string(in.AccountName))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PendingInviteView) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PendingInviteView) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PendingInviteView) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PendingInviteView) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels8(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(in *jlexer.Lexer, out *MemberResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "username":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Username = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Email = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "is_owner":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsOwner = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(out *jwriter.Writer, in MemberResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"username\":"
		out.RawString(prefix)
		out.String(string(in.Username))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"is_owner\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsOwner))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MemberResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MemberResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MemberResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MemberResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels9(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(in *jlexer.Lexer, out *InviteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Users":
			if in.IsNull() {
				in.Skip()
				out.Users = nil
			} else {
				in.Delim('[')
				if out.Users == nil {
					if !in.IsDelim(']') {
						out.Users = make([]UserSearchResult, 0, 1)
					} else {
						out.Users = []UserSearchResult{}
					}
				} else {
					out.Users = (out.Users)[:0]
				}
				for !in.IsDelim(']') {
					var v4 UserSearchResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Users = append(out.Users, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(out *jwriter.Writer, in InviteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Users\":"
		out.RawString(prefix[1:])
		if in.Users == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Users {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InviteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InviteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InviteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InviteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels10(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(in *jlexer.Lexer, out *InviteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "query":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Query = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(out *jwriter.Writer, in InviteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"query\":"
		out.RawString(prefix[1:])
		out.String(string(in.Query))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v InviteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v InviteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *InviteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *InviteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels11(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(in *jlexer.Lexer, out *CurrencyStat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = float64(in.Float64())
			}
		case "Income":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Income = float64(in.Float64())
			}
		case "Expenses":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Expenses = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(out *jwriter.Writer, in CurrencyStat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix[1:])
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Float64(float64(in.Balance))
	}
	{
		const prefix string = ",\"Income\":"
		out.RawString(prefix)
		out.Float64(float64(in.Income))
	}
	{
		const prefix string = ",\"Expenses\":"
		out.RawString(prefix)
		out.Float64(float64(in.Expenses))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CurrencyStat) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CurrencyStat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CurrencyStat) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CurrencyStat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels12(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(in *jlexer.Lexer, out *BudgetModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "StartAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.StartAt).UnmarshalJSON(data))
				}
			}
		case "EndAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EndAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		case "Actual":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Actual = float64(in.Float64())
			}
		case "Target":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Target = float64(in.Float64())
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "Author":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Author = int(in.Int())
			}
		case "Active":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Active = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(out *jwriter.Writer, in BudgetModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"StartAt\":"
		out.RawString(prefix)
		out.Raw((in.StartAt).MarshalJSON())
	}
	{
		const prefix string = ",\"EndAt\":"
		out.RawString(prefix)
		out.Raw((in.EndAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"Actual\":"
		out.RawString(prefix)
		out.Float64(float64(in.Actual))
	}
	{
		const prefix string = ",\"Target\":"
		out.RawString(prefix)
		out.Float64(float64(in.Target))
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"Author\":"
		out.RawString(prefix)
		out.Int(int(in.Author))
	}
	{
		const prefix string = ",\"Active\":"
		out.RawString(prefix)
		out.Bool(bool(in.Active))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BudgetModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BudgetModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BudgetModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BudgetModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels13(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(in *jlexer.Lexer, out *BucketModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int(in.Int())
			}
		case "LastRefillTime":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastRefillTime).UnmarshalJSON(data))
				}
			}
		case "BlockedUntil":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BlockedUntil).UnmarshalJSON(data))
				}
			}
		case "LastSeen":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastSeen).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(out *jwriter.Writer, in BucketModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"LastRefillTime\":"
		out.RawString(prefix)
		out.Raw((in.LastRefillTime).MarshalJSON())
	}
	{
		const prefix string = ",\"BlockedUntil\":"
		out.RawString(prefix)
		out.Raw((in.BlockedUntil).MarshalJSON())
	}
	{
		const prefix string = ",\"LastSeen\":"
		out.RawString(prefix)
		out.Raw((in.LastSeen).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BucketModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BucketModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BucketModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BucketModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels14(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(in *jlexer.Lexer, out *AccountUserUpdateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Status = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(out *jwriter.Writer, in AccountUserUpdateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix[1:])
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserUpdateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserUpdateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserUpdateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserUpdateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels15(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(in *jlexer.Lexer, out *AccountUserModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "account_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(out *jwriter.Writer, in AccountUserModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels16(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(in *jlexer.Lexer, out *AccountUserCreateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "AccountId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(out *jwriter.Writer, in AccountUserCreateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"AccountId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUserCreateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUserCreateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUserCreateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUserCreateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels17(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(in *jlexer.Lexer, out *AccountUpdateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
				out.Balance = nil
			} else {
				if out.Balance == nil {
					out.Balance = new(float64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Balance = float64(in.Float64())
				}
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
				out.Currency = nil
			} else {
				if out.Currency == nil {
					out.Currency = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Currency = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(out *jwriter.Writer, in AccountUpdateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		if in.Balance == nil {
			out.RawString("null")
		} else {
			out.Float64(float64(*in.Balance))
		}
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		if in.Currency == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Currency))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountUpdateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountUpdateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountUpdateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountUpdateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels18(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(in *jlexer.Lexer, out *AccountModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = float64(in.Float64())
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "OwnerId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerId = int(in.Int())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(out *jwriter.Writer, in AccountModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Float64(float64(in.Balance))
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"OwnerId\":"
		out.RawString(prefix)
		out.Int(int(in.OwnerId))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels19(l, v)
}
func easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(in *jlexer.Lexer, out *AccountCreateModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "Balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = float64(in.Float64())
			}
		case "Currency":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Currency = string(in.String())
			}
		case "OwnerId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerId = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(out *jwriter.Writer, in AccountCreateModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Balance\":"
		out.RawString(prefix)
		out.Float64(float64(in.Balance))
	}
	{
		const prefix string = ",\"Currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"OwnerId\":"
		out.RawString(prefix)
		out.Int(int(in.OwnerId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccountCreateModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccountCreateModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccountCreateModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccountCreateModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels20(l, v)
}
