// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *PermanentBlockedIps) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Ips":
			if in.IsNull() {
				in.Skip()
				out.Ips = nil
			} else {
				in.Delim('[')
				if out.Ips == nil {
					if !in.IsDelim(']') {
						out.Ips = make([]string, 0, 4)
					} else {
						out.Ips = []string{}
					}
				} else {
					out.Ips = (out.Ips)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Ips = append(out.Ips, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in PermanentBlockedIps) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Ips\":"
		out.RawString(prefix[1:])
		if in.Ips == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Ips {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PermanentBlockedIps) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PermanentBlockedIps) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PermanentBlockedIps) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PermanentBlockedIps) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
func easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(in *jlexer.Lexer, out *BucketModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Count = int(in.Int())
			}
		case "LastRefillTime":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastRefillTime).UnmarshalJSON(data))
				}
			}
		case "BlockedUntil":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BlockedUntil).UnmarshalJSON(data))
				}
			}
		case "LastSeen":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.LastSeen).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(out *jwriter.Writer, in BucketModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Count\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Count))
	}
	{
		const prefix string = ",\"LastRefillTime\":"
		out.RawString(prefix)
		out.Raw((in.LastRefillTime).MarshalJSON())
	}
	{
		const prefix string = ",\"BlockedUntil\":"
		out.RawString(prefix)
		out.Raw((in.BlockedUntil).MarshalJSON())
	}
	{
		const prefix string = ",\"LastSeen\":"
		out.RawString(prefix)
		out.Raw((in.LastSeen).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BucketModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BucketModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD1f0e8afEncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BucketModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BucketModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD1f0e8afDecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(l, v)
}
