// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(in *jlexer.Lexer, out *TransactionModel) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = int(in.Int())
			}
		case "UserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserId = int(in.Int())
			}
		case "AccountId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountId = int(in.Int())
			}
		case "Value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "Type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "Category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "Title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "Description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "CreatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		case "TransactionDate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TransactionDate).UnmarshalJSON(data))
				}
			}
		case "DeletedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.DeletedAt).UnmarshalJSON(data))
				}
			}
		case "UpdatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(out *jwriter.Writer, in TransactionModel) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Id))
	}
	{
		const prefix string = ",\"UserId\":"
		out.RawString(prefix)
		out.Int(int(in.UserId))
	}
	{
		const prefix string = ",\"AccountId\":"
		out.RawString(prefix)
		out.Int(int(in.AccountId))
	}
	{
		const prefix string = ",\"Value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"Type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"Category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"Title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"Description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"CreatedAt\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"TransactionDate\":"
		out.RawString(prefix)
		out.Raw((in.TransactionDate).MarshalJSON())
	}
	{
		const prefix string = ",\"DeletedAt\":"
		out.RawString(prefix)
		out.Raw((in.DeletedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"UpdatedAt\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TransactionModel) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TransactionModel) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TransactionModel) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TransactionModel) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels(l, v)
}
func easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(in *jlexer.Lexer, out *TransactionDraft) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "raw_text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawText = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "recorded_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.RecordedAt).UnmarshalJSON(data))
				}
			}
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Date).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(out *jwriter.Writer, in TransactionDraft) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"raw_text\":"
		out.RawString(prefix[1:])
		out.String(string(in.RawText))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"recorded_at\":"
		out.RawString(prefix)
		out.Raw((in.RecordedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.Raw((in.Date).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TransactionDraft) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TransactionDraft) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson461f4b12EncodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TransactionDraft) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TransactionDraft) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson461f4b12DecodeGithubComGoParkMailRu20261GPTeamInternalApplicationModels1(l, v)
}
