// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package groq

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(in *jlexer.Lexer, out *parsedDraft) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = float64(in.Float64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Category = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "date":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Date = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(out *jwriter.Writer, in parsedDraft) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.Value))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v parsedDraft) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v parsedDraft) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *parsedDraft) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *parsedDraft) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq(l, v)
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(in *jlexer.Lexer, out *groqTranscriptResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(out *jwriter.Writer, in groqTranscriptResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v groqTranscriptResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v groqTranscriptResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *groqTranscriptResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *groqTranscriptResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq1(l, v)
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(in *jlexer.Lexer, out *groqErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			easyjsonFa8be3edDecode(in, &out.Error)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(out *jwriter.Writer, in groqErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		easyjsonFa8be3edEncode(out, in.Error)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v groqErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v groqErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *groqErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *groqErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq2(l, v)
}
func easyjsonFa8be3edDecode(in *jlexer.Lexer, out *struct {
	Message string `json:"message"`
	Type    string `json:"type"`
	Code    string `json:"code"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncode(out *jwriter.Writer, in struct {
	Message string `json:"message"`
	Type    string `json:"type"`
	Code    string `json:"code"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	out.RawByte('}')
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(in *jlexer.Lexer, out *groqChatResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "choices":
			if in.IsNull() {
				in.Skip()
				out.Choices = nil
			} else {
				in.Delim('[')
				if out.Choices == nil {
					if !in.IsDelim(']') {
						out.Choices = make([]struct {
							Message chatMessage `json:"message"`
						}, 0, 2)
					} else {
						out.Choices = []struct {
							Message chatMessage `json:"message"`
						}{}
					}
				} else {
					out.Choices = (out.Choices)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Message chatMessage `json:"message"`
					}
					easyjsonFa8be3edDecode1(in, &v1)
					out.Choices = append(out.Choices, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(out *jwriter.Writer, in groqChatResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"choices\":"
		out.RawString(prefix[1:])
		if in.Choices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Choices {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjsonFa8be3edEncode1(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v groqChatResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v groqChatResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *groqChatResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *groqChatResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq3(l, v)
}
func easyjsonFa8be3edDecode1(in *jlexer.Lexer, out *struct {
	Message chatMessage `json:"message"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Message).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncode1(out *jwriter.Writer, in struct {
	Message chatMessage `json:"message"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		(in.Message).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(in *jlexer.Lexer, out *groqChatRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "model":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Model = string(in.String())
			}
		case "messages":
			if in.IsNull() {
				in.Skip()
				out.Messages = nil
			} else {
				in.Delim('[')
				if out.Messages == nil {
					if !in.IsDelim(']') {
						out.Messages = make([]chatMessage, 0, 2)
					} else {
						out.Messages = []chatMessage{}
					}
				} else {
					out.Messages = (out.Messages)[:0]
				}
				for !in.IsDelim(']') {
					var v4 chatMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Messages = append(out.Messages, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "temperature":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Temperature = float64(in.Float64())
			}
		case "max_tokens":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxTokens = int(in.Int())
			}
		case "top_p":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TopP = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(out *jwriter.Writer, in groqChatRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"model\":"
		out.RawString(prefix[1:])
		out.String(string(in.Model))
	}
	{
		const prefix string = ",\"messages\":"
		out.RawString(prefix)
		if in.Messages == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Messages {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"temperature\":"
		out.RawString(prefix)
		out.Float64(float64(in.Temperature))
	}
	{
		const prefix string = ",\"max_tokens\":"
		out.RawString(prefix)
		out.Int(int(in.MaxTokens))
	}
	{
		const prefix string = ",\"top_p\":"
		out.RawString(prefix)
		out.Float64(float64(in.TopP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v groqChatRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v groqChatRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *groqChatRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *groqChatRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq4(l, v)
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(in *jlexer.Lexer, out *chatMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(out *jwriter.Writer, in chatMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v chatMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v chatMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *chatMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *chatMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq5(l, v)
}
func easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(in *jlexer.Lexer, out *GroqClient) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(out *jwriter.Writer, in GroqClient) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GroqClient) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GroqClient) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFa8be3edEncodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GroqClient) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GroqClient) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFa8be3edDecodeGithubComGoParkMailRu20261GPTeamInternalAiGroq6(l, v)
}
