// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -source=jwt.go -destination=mocks/jwt.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtUseCase is a mock of JwtUseCase interface.
type MockJwtUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockJwtUseCaseMockRecorder
	isgomock struct{}
}

// MockJwtUseCaseMockRecorder is the mock recorder for MockJwtUseCase.
type MockJwtUseCaseMockRecorder struct {
	mock *MockJwtUseCase
}

// NewMockJwtUseCase creates a new mock instance.
func NewMockJwtUseCase(ctrl *gomock.Controller) *MockJwtUseCase {
	mock := &MockJwtUseCase{ctrl: ctrl}
	mock.recorder = &MockJwtUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtUseCase) EXPECT() *MockJwtUseCaseMockRecorder {
	return m.recorder
}

// CheckRefreshToken mocks base method.
func (m *MockJwtUseCase) CheckRefreshToken(ctx context.Context, tokenStr string) (bool, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRefreshToken", ctx, tokenStr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// CheckRefreshToken indicates an expected call of CheckRefreshToken.
func (mr *MockJwtUseCaseMockRecorder) CheckRefreshToken(ctx, tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRefreshToken", reflect.TypeOf((*MockJwtUseCase)(nil).CheckRefreshToken), ctx, tokenStr)
}

// CheckToken mocks base method.
func (m *MockJwtUseCase) CheckToken(tokenStr string) (bool, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckToken", tokenStr)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// CheckToken indicates an expected call of CheckToken.
func (mr *MockJwtUseCaseMockRecorder) CheckToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckToken", reflect.TypeOf((*MockJwtUseCase)(nil).CheckToken), tokenStr)
}

// DeleteRefreshToken mocks base method.
func (m *MockJwtUseCase) DeleteRefreshToken(ctx context.Context, tokenStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshToken", ctx, tokenStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshToken indicates an expected call of DeleteRefreshToken.
func (mr *MockJwtUseCaseMockRecorder) DeleteRefreshToken(ctx, tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshToken", reflect.TypeOf((*MockJwtUseCase)(nil).DeleteRefreshToken), ctx, tokenStr)
}

// GenerateRefreshToken mocks base method.
func (m *MockJwtUseCase) GenerateRefreshToken(ctx context.Context, userId int, deviceId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", ctx, userId, deviceId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJwtUseCaseMockRecorder) GenerateRefreshToken(ctx, userId, deviceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJwtUseCase)(nil).GenerateRefreshToken), ctx, userId, deviceId)
}

// GenerateToken mocks base method.
func (m *MockJwtUseCase) GenerateToken(userId int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJwtUseCaseMockRecorder) GenerateToken(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJwtUseCase)(nil).GenerateToken), userId)
}

// GetJWTSecret mocks base method.
func (m *MockJwtUseCase) GetJWTSecret() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJWTSecret")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GetJWTSecret indicates an expected call of GetJWTSecret.
func (mr *MockJwtUseCaseMockRecorder) GetJWTSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJWTSecret", reflect.TypeOf((*MockJwtUseCase)(nil).GetJWTSecret))
}

// GetVersion mocks base method.
func (m *MockJwtUseCase) GetVersion() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockJwtUseCaseMockRecorder) GetVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockJwtUseCase)(nil).GetVersion))
}

// parseToken mocks base method.
func (m *MockJwtUseCase) parseToken(tokenStr string) (*jwt.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "parseToken", tokenStr)
	ret0, _ := ret[0].(*jwt.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// parseToken indicates an expected call of parseToken.
func (mr *MockJwtUseCaseMockRecorder) parseToken(tokenStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "parseToken", reflect.TypeOf((*MockJwtUseCase)(nil).parseToken), tokenStr)
}
