// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mocks/mock_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvatarUseCase is a mock of AvatarUseCase interface.
type MockAvatarUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUseCaseMockRecorder
	isgomock struct{}
}

// MockAvatarUseCaseMockRecorder is the mock recorder for MockAvatarUseCase.
type MockAvatarUseCaseMockRecorder struct {
	mock *MockAvatarUseCase
}

// NewMockAvatarUseCase creates a new mock instance.
func NewMockAvatarUseCase(ctrl *gomock.Controller) *MockAvatarUseCase {
	mock := &MockAvatarUseCase{ctrl: ctrl}
	mock.recorder = &MockAvatarUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUseCase) EXPECT() *MockAvatarUseCaseMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockAvatarUseCase) Upload(ctx context.Context, data []byte, extension string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, data, extension)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarUseCaseMockRecorder) Upload(ctx, data, extension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarUseCase)(nil).Upload), ctx, data, extension)
}
