// Code generated by MockGen. DO NOT EDIT.
// Source: internal/secure/csrf.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCsrfService is a mock of CsrfService interface.
type MockCsrfService struct {
	ctrl     *gomock.Controller
	recorder *MockCsrfServiceMockRecorder
}

// MockCsrfServiceMockRecorder is the mock recorder for MockCsrfService.
type MockCsrfServiceMockRecorder struct {
	mock *MockCsrfService
}

// NewMockCsrfService creates a new mock instance.
func NewMockCsrfService(ctrl *gomock.Controller) *MockCsrfService {
	mock := &MockCsrfService{ctrl: ctrl}
	mock.recorder = &MockCsrfServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCsrfService) EXPECT() *MockCsrfServiceMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockCsrfService) GetAccessToken(ctx context.Context, r *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx, r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockCsrfServiceMockRecorder) GetAccessToken(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockCsrfService)(nil).GetAccessToken), ctx, r)
}

// GetCsrfFromCookie mocks base method.
func (m *MockCsrfService) GetCsrfFromCookie(ctx context.Context, r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCsrfFromCookie", ctx, r)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCsrfFromCookie indicates an expected call of GetCsrfFromCookie.
func (mr *MockCsrfServiceMockRecorder) GetCsrfFromCookie(ctx, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCsrfFromCookie", reflect.TypeOf((*MockCsrfService)(nil).GetCsrfFromCookie), ctx, r)
}

// GetCsrfFromHeader mocks base method.
func (m *MockCsrfService) GetCsrfFromHeader(r *http.Request) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCsrfFromHeader", r)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCsrfFromHeader indicates an expected call of GetCsrfFromHeader.
func (mr *MockCsrfServiceMockRecorder) GetCsrfFromHeader(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCsrfFromHeader", reflect.TypeOf((*MockCsrfService)(nil).GetCsrfFromHeader), r)
}

// SetCsrfCookie mocks base method.
func (m *MockCsrfService) SetCsrfCookie(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCsrfCookie", ctx, w, r)
}

// SetCsrfCookie indicates an expected call of SetCsrfCookie.
func (mr *MockCsrfServiceMockRecorder) SetCsrfCookie(ctx, w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCsrfCookie", reflect.TypeOf((*MockCsrfService)(nil).SetCsrfCookie), ctx, w, r)
}

// ValidateCsrf mocks base method.
func (m *MockCsrfService) ValidateCsrf(ctx context.Context, csrf, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCsrf", ctx, csrf, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateCsrf indicates an expected call of ValidateCsrf.
func (mr *MockCsrfServiceMockRecorder) ValidateCsrf(ctx, csrf, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCsrf", reflect.TypeOf((*MockCsrfService)(nil).ValidateCsrf), ctx, csrf, token)
}

// ValidateSecFetchSite mocks base method.
func (m *MockCsrfService) ValidateSecFetchSite(r *http.Request) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSecFetchSite", r)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateSecFetchSite indicates an expected call of ValidateSecFetchSite.
func (mr *MockCsrfServiceMockRecorder) ValidateSecFetchSite(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSecFetchSite", reflect.TypeOf((*MockCsrfService)(nil).ValidateSecFetchSite), r)
}
