// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2026_1_GPTeam/internal/application (interfaces: AccountUseCase,AccountUserUseCase)

// Package appmocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountUseCase is a mock of AccountUseCase interface.
type MockAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUseCaseMockRecorder
}

// MockAccountUseCaseMockRecorder is the mock recorder for MockAccountUseCase.
type MockAccountUseCaseMockRecorder struct {
	mock *MockAccountUseCase
}

// NewMockAccountUseCase creates a new mock instance.
func NewMockAccountUseCase(ctrl *gomock.Controller) *MockAccountUseCase {
	mock := &MockAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUseCase) EXPECT() *MockAccountUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountUseCase) Create(arg0 context.Context, arg1 models.AccountModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountUseCaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountUseCase)(nil).Create), arg0, arg1)
}

// CreateForUser mocks base method.
func (m *MockAccountUseCase) CreateForUser(arg0 context.Context, arg1 int, arg2 models.AccountCreateModel) (models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateForUser indicates an expected call of CreateForUser.
func (mr *MockAccountUseCaseMockRecorder) CreateForUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForUser", reflect.TypeOf((*MockAccountUseCase)(nil).CreateForUser), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockAccountUseCase) Delete(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountUseCaseMockRecorder) Delete(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccountUseCase)(nil).Delete), arg0, arg1, arg2)
}

// GetAccountIdByUserId mocks base method.
func (m *MockAccountUseCase) GetAccountIdByUserId(arg0 context.Context, arg1 int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIdByUserId", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdByUserId indicates an expected call of GetAccountIdByUserId.
func (mr *MockAccountUseCaseMockRecorder) GetAccountIdByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdByUserId", reflect.TypeOf((*MockAccountUseCase)(nil).GetAccountIdByUserId), arg0, arg1)
}

// GetAllAccountsByUserId mocks base method.
func (m *MockAccountUseCase) GetAllAccountsByUserId(arg0 context.Context, arg1 int) ([]models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountsByUserId", arg0, arg1)
	ret0, _ := ret[0].([]models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllAccountsByUserId indicates an expected call of GetAllAccountsByUserId.
func (mr *MockAccountUseCaseMockRecorder) GetAllAccountsByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountsByUserId", reflect.TypeOf((*MockAccountUseCase)(nil).GetAllAccountsByUserId), arg0, arg1)
}

// GetAllAccountsByUserIdWithBalance mocks base method.
func (m *MockAccountUseCase) GetAllAccountsByUserIdWithBalance(arg0 context.Context, arg1 int) ([]models.AccountModel, []float64, []float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllAccountsByUserIdWithBalance", arg0, arg1)
	ret0, _ := ret[0].([]models.AccountModel)
	ret1, _ := ret[1].([]float64)
	ret2, _ := ret[2].([]float64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetAllAccountsByUserIdWithBalance indicates an expected call of GetAllAccountsByUserIdWithBalance.
func (mr *MockAccountUseCaseMockRecorder) GetAllAccountsByUserIdWithBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllAccountsByUserIdWithBalance", reflect.TypeOf((*MockAccountUseCase)(nil).GetAllAccountsByUserIdWithBalance), arg0, arg1)
}

// GetById mocks base method.
func (m *MockAccountUseCase) GetById(arg0 context.Context, arg1, arg2 int) (models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAccountUseCaseMockRecorder) GetById(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAccountUseCase)(nil).GetById), arg0, arg1, arg2)
}

// GetByUserId mocks base method.
func (m *MockAccountUseCase) GetByUserId(arg0 context.Context, arg1 int) ([]models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserId", arg0, arg1)
	ret0, _ := ret[0].([]models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserId indicates an expected call of GetByUserId.
func (mr *MockAccountUseCaseMockRecorder) GetByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserId", reflect.TypeOf((*MockAccountUseCase)(nil).GetByUserId), arg0, arg1)
}

// GetCurrencyByAccountId mocks base method.
func (m *MockAccountUseCase) GetCurrencyByAccountId(arg0 context.Context, arg1 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyByAccountId", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencyByAccountId indicates an expected call of GetCurrencyByAccountId.
func (mr *MockAccountUseCaseMockRecorder) GetCurrencyByAccountId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyByAccountId", reflect.TypeOf((*MockAccountUseCase)(nil).GetCurrencyByAccountId), arg0, arg1)
}

// IsUserAuthorOfAccount mocks base method.
func (m *MockAccountUseCase) IsUserAuthorOfAccount(arg0 context.Context, arg1, arg2 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAuthorOfAccount indicates an expected call of IsUserAuthorOfAccount.
func (mr *MockAccountUseCaseMockRecorder) IsUserAuthorOfAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfAccount", reflect.TypeOf((*MockAccountUseCase)(nil).IsUserAuthorOfAccount), arg0, arg1, arg2)
}

// LinkAccountAndUser mocks base method.
func (m *MockAccountUseCase) LinkAccountAndUser(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAccountAndUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAccountAndUser indicates an expected call of LinkAccountAndUser.
func (mr *MockAccountUseCaseMockRecorder) LinkAccountAndUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAccountAndUser", reflect.TypeOf((*MockAccountUseCase)(nil).LinkAccountAndUser), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockAccountUseCase) Update(arg0 context.Context, arg1, arg2 int, arg3 models.AccountUpdateModel) (models.AccountModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(models.AccountModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountUseCaseMockRecorder) Update(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountUseCase)(nil).Update), arg0, arg1, arg2, arg3)
}

// MockAccountUserUseCase is a mock of AccountUserUseCase interface.
type MockAccountUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUserUseCaseMockRecorder
}

// MockAccountUserUseCaseMockRecorder is the mock recorder for MockAccountUserUseCase.
type MockAccountUserUseCaseMockRecorder struct {
	mock *MockAccountUserUseCase
}

// NewMockAccountUserUseCase creates a new mock instance.
func NewMockAccountUserUseCase(ctrl *gomock.Controller) *MockAccountUserUseCase {
	mock := &MockAccountUserUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUserUseCase) EXPECT() *MockAccountUserUseCaseMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockAccountUserUseCase) AcceptInvite(arg0 context.Context, arg1, arg2 int) (models.AccountUserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.AccountUserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockAccountUserUseCaseMockRecorder) AcceptInvite(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).AcceptInvite), arg0, arg1, arg2)
}

// CreateInvite mocks base method.
func (m *MockAccountUserUseCase) CreateInvite(arg0 context.Context, arg1, arg2, arg3 int) (models.AccountUserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(models.AccountUserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockAccountUserUseCaseMockRecorder) CreateInvite(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).CreateInvite), arg0, arg1, arg2, arg3)
}

// GetMembers mocks base method.
func (m *MockAccountUserUseCase) GetMembers(arg0 context.Context, arg1, arg2 int) ([]models.MemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.MemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockAccountUserUseCaseMockRecorder) GetMembers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockAccountUserUseCase)(nil).GetMembers), arg0, arg1, arg2)
}

// GetPendingInvites mocks base method.
func (m *MockAccountUserUseCase) GetPendingInvites(arg0 context.Context, arg1 int) ([]models.PendingInviteView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingInvites", arg0, arg1)
	ret0, _ := ret[0].([]models.PendingInviteView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingInvites indicates an expected call of GetPendingInvites.
func (mr *MockAccountUserUseCaseMockRecorder) GetPendingInvites(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingInvites", reflect.TypeOf((*MockAccountUserUseCase)(nil).GetPendingInvites), arg0, arg1)
}

// LeaveAccount mocks base method.
func (m *MockAccountUserUseCase) LeaveAccount(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveAccount", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveAccount indicates an expected call of LeaveAccount.
func (mr *MockAccountUserUseCaseMockRecorder) LeaveAccount(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveAccount", reflect.TypeOf((*MockAccountUserUseCase)(nil).LeaveAccount), arg0, arg1, arg2)
}

// RejectInvite mocks base method.
func (m *MockAccountUserUseCase) RejectInvite(arg0 context.Context, arg1, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectInvite", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectInvite indicates an expected call of RejectInvite.
func (mr *MockAccountUserUseCaseMockRecorder) RejectInvite(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).RejectInvite), arg0, arg1, arg2)
}

// RemoveMember mocks base method.
func (m *MockAccountUserUseCase) RemoveMember(arg0 context.Context, arg1, arg2, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockAccountUserUseCaseMockRecorder) RemoveMember(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockAccountUserUseCase)(nil).RemoveMember), arg0, arg1, arg2, arg3)
}

// SearchUsers mocks base method.
func (m *MockAccountUserUseCase) SearchUsers(arg0 context.Context, arg1 int, arg2 string, arg3 int) ([]models.UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]models.UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockAccountUserUseCaseMockRecorder) SearchUsers(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockAccountUserUseCase)(nil).SearchUsers), arg0, arg1, arg2, arg3)
}
