// Code generated by MockGen. DO NOT EDIT.
// Source: account.go
//
// Generated by this command:
//
//	mockgen -source=account.go -destination=mocks/account.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountUseCase is a mock of AccountUseCase interface.
type MockAccountUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUseCaseMockRecorder
	isgomock struct{}
}

// MockAccountUseCaseMockRecorder is the mock recorder for MockAccountUseCase.
type MockAccountUseCaseMockRecorder struct {
	mock *MockAccountUseCase
}

// NewMockAccountUseCase creates a new mock instance.
func NewMockAccountUseCase(ctrl *gomock.Controller) *MockAccountUseCase {
	mock := &MockAccountUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUseCase) EXPECT() *MockAccountUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAccountUseCase) Create(ctx context.Context, account models.AccountModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, account)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAccountUseCaseMockRecorder) Create(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccountUseCase)(nil).Create), ctx, account)
}

// GetAccountIdByUserId mocks base method.
func (m *MockAccountUseCase) GetAccountIdByUserId(ctx context.Context, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountIdByUserId", ctx, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountIdByUserId indicates an expected call of GetAccountIdByUserId.
func (mr *MockAccountUseCaseMockRecorder) GetAccountIdByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountIdByUserId", reflect.TypeOf((*MockAccountUseCase)(nil).GetAccountIdByUserId), ctx, userId)
}

// IsUserAuthorOfAccount mocks base method.
func (m *MockAccountUseCase) IsUserAuthorOfAccount(ctx context.Context, userId, accountId int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfAccount", ctx, userId, accountId)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAuthorOfAccount indicates an expected call of IsUserAuthorOfAccount.
func (mr *MockAccountUseCaseMockRecorder) IsUserAuthorOfAccount(ctx, userId, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfAccount", reflect.TypeOf((*MockAccountUseCase)(nil).IsUserAuthorOfAccount), ctx, userId, accountId)
}

// LinkAccountAndUser mocks base method.
func (m *MockAccountUseCase) LinkAccountAndUser(ctx context.Context, accountId, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAccountAndUser", ctx, accountId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAccountAndUser indicates an expected call of LinkAccountAndUser.
func (mr *MockAccountUseCaseMockRecorder) LinkAccountAndUser(ctx, accountId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAccountAndUser", reflect.TypeOf((*MockAccountUseCase)(nil).LinkAccountAndUser), ctx, accountId, userId)
}
