// Code generated by MockGen. DO NOT EDIT.
// Source: budget.go
//
// Generated by this command:
//
//	mockgen -source=budget.go -destination=mocks/budget.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetUseCase is a mock of BudgetUseCase interface.
type MockBudgetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetUseCaseMockRecorder
	isgomock struct{}
}

// MockBudgetUseCaseMockRecorder is the mock recorder for MockBudgetUseCase.
type MockBudgetUseCaseMockRecorder struct {
	mock *MockBudgetUseCase
}

// NewMockBudgetUseCase creates a new mock instance.
func NewMockBudgetUseCase(ctrl *gomock.Controller) *MockBudgetUseCase {
	mock := &MockBudgetUseCase{ctrl: ctrl}
	mock.recorder = &MockBudgetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetUseCase) EXPECT() *MockBudgetUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBudgetUseCase) Create(ctx context.Context, budget models.BudgetModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, budget)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBudgetUseCaseMockRecorder) Create(ctx, budget any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBudgetUseCase)(nil).Create), ctx, budget)
}

// Delete mocks base method.
func (m *MockBudgetUseCase) Delete(ctx context.Context, budgetId int, user models.UserModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, budgetId, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBudgetUseCaseMockRecorder) Delete(ctx, budgetId, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBudgetUseCase)(nil).Delete), ctx, budgetId, user)
}

// GetBudgetsOfUser mocks base method.
func (m *MockBudgetUseCase) GetBudgetsOfUser(ctx context.Context, user models.UserModel) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetsOfUser", ctx, user)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetsOfUser indicates an expected call of GetBudgetsOfUser.
func (mr *MockBudgetUseCaseMockRecorder) GetBudgetsOfUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetsOfUser", reflect.TypeOf((*MockBudgetUseCase)(nil).GetBudgetsOfUser), ctx, user)
}

// GetById mocks base method.
func (m *MockBudgetUseCase) GetById(ctx context.Context, id int, user models.UserModel) (models.BudgetModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id, user)
	ret0, _ := ret[0].(models.BudgetModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockBudgetUseCaseMockRecorder) GetById(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockBudgetUseCase)(nil).GetById), ctx, id, user)
}

// IsUserAuthorOfBudget mocks base method.
func (m *MockBudgetUseCase) IsUserAuthorOfBudget(budget models.BudgetModel, user models.UserModel) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfBudget", budget, user)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAuthorOfBudget indicates an expected call of IsUserAuthorOfBudget.
func (mr *MockBudgetUseCaseMockRecorder) IsUserAuthorOfBudget(budget, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfBudget", reflect.TypeOf((*MockBudgetUseCase)(nil).IsUserAuthorOfBudget), budget, user)
}
