// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/account_user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAccountUserUseCase is a mock of AccountUserUseCase interface.
type MockAccountUserUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAccountUserUseCaseMockRecorder
}

// MockAccountUserUseCaseMockRecorder is the mock recorder for MockAccountUserUseCase.
type MockAccountUserUseCaseMockRecorder struct {
	mock *MockAccountUserUseCase
}

// NewMockAccountUserUseCase creates a new mock instance.
func NewMockAccountUserUseCase(ctrl *gomock.Controller) *MockAccountUserUseCase {
	mock := &MockAccountUserUseCase{ctrl: ctrl}
	mock.recorder = &MockAccountUserUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountUserUseCase) EXPECT() *MockAccountUserUseCaseMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockAccountUserUseCase) AcceptInvite(ctx context.Context, accountId, userId int) (models.AccountUserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, accountId, userId)
	ret0, _ := ret[0].(models.AccountUserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockAccountUserUseCaseMockRecorder) AcceptInvite(ctx, accountId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).AcceptInvite), ctx, accountId, userId)
}

// CreateInvite mocks base method.
func (m *MockAccountUserUseCase) CreateInvite(ctx context.Context, accountId, ownerId, targetUserId int) (models.AccountUserModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, accountId, ownerId, targetUserId)
	ret0, _ := ret[0].(models.AccountUserModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockAccountUserUseCaseMockRecorder) CreateInvite(ctx, accountId, ownerId, targetUserId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).CreateInvite), ctx, accountId, ownerId, targetUserId)
}

// GetMembers mocks base method.
func (m *MockAccountUserUseCase) GetMembers(ctx context.Context, accountId, requestingUserId int) ([]models.MemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers", ctx, accountId, requestingUserId)
	ret0, _ := ret[0].([]models.MemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers.
func (mr *MockAccountUserUseCaseMockRecorder) GetMembers(ctx, accountId, requestingUserId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockAccountUserUseCase)(nil).GetMembers), ctx, accountId, requestingUserId)
}

// GetPendingInvites mocks base method.
func (m *MockAccountUserUseCase) GetPendingInvites(ctx context.Context, userId int) ([]models.PendingInviteView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingInvites", ctx, userId)
	ret0, _ := ret[0].([]models.PendingInviteView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingInvites indicates an expected call of GetPendingInvites.
func (mr *MockAccountUserUseCaseMockRecorder) GetPendingInvites(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingInvites", reflect.TypeOf((*MockAccountUserUseCase)(nil).GetPendingInvites), ctx, userId)
}

// LeaveAccount mocks base method.
func (m *MockAccountUserUseCase) LeaveAccount(ctx context.Context, accountId, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveAccount", ctx, accountId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveAccount indicates an expected call of LeaveAccount.
func (mr *MockAccountUserUseCaseMockRecorder) LeaveAccount(ctx, accountId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveAccount", reflect.TypeOf((*MockAccountUserUseCase)(nil).LeaveAccount), ctx, accountId, userId)
}

// RejectInvite mocks base method.
func (m *MockAccountUserUseCase) RejectInvite(ctx context.Context, accountId, userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectInvite", ctx, accountId, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectInvite indicates an expected call of RejectInvite.
func (mr *MockAccountUserUseCaseMockRecorder) RejectInvite(ctx, accountId, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectInvite", reflect.TypeOf((*MockAccountUserUseCase)(nil).RejectInvite), ctx, accountId, userId)
}

// RemoveMember mocks base method.
func (m *MockAccountUserUseCase) RemoveMember(ctx context.Context, accountId, ownerId, targetUserId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, accountId, ownerId, targetUserId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockAccountUserUseCaseMockRecorder) RemoveMember(ctx, accountId, ownerId, targetUserId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockAccountUserUseCase)(nil).RemoveMember), ctx, accountId, ownerId, targetUserId)
}

// SearchUsers mocks base method.
func (m *MockAccountUserUseCase) SearchUsers(ctx context.Context, accountId int, query string, limit int) ([]models.UserSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, accountId, query, limit)
	ret0, _ := ret[0].([]models.UserSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockAccountUserUseCaseMockRecorder) SearchUsers(ctx, accountId, query, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockAccountUserUseCase)(nil).SearchUsers), ctx, accountId, query, limit)
}
