// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -source=transaction.go -destination=mocks/mock_transaction.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	repository "github.com/go-park-mail-ru/2026_1_GPTeam/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionUseCase is a mock of TransactionUseCase interface.
type MockTransactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUseCaseMockRecorder
	isgomock struct{}
}

// MockTransactionUseCaseMockRecorder is the mock recorder for MockTransactionUseCase.
type MockTransactionUseCaseMockRecorder struct {
	mock *MockTransactionUseCase
}

// NewMockTransactionUseCase creates a new mock instance.
func NewMockTransactionUseCase(ctrl *gomock.Controller) *MockTransactionUseCase {
	mock := &MockTransactionUseCase{ctrl: ctrl}
	mock.recorder = &MockTransactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionUseCase) EXPECT() *MockTransactionUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionUseCase) Create(ctx context.Context, transaction models.TransactionModel) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, transaction)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTransactionUseCaseMockRecorder) Create(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionUseCase)(nil).Create), ctx, transaction)
}

// Delete mocks base method.
func (m *MockTransactionUseCase) Delete(ctx context.Context, transactionId, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, transactionId, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTransactionUseCaseMockRecorder) Delete(ctx, transactionId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTransactionUseCase)(nil).Delete), ctx, transactionId, userId)
}

// Detail mocks base method.
func (m *MockTransactionUseCase) Detail(ctx context.Context, transactionId, userId int) (models.TransactionModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, transactionId, userId)
	ret0, _ := ret[0].(models.TransactionModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockTransactionUseCaseMockRecorder) Detail(ctx, transactionId, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockTransactionUseCase)(nil).Detail), ctx, transactionId, userId)
}

// GetTransactionIdsOfUser mocks base method.
func (m *MockTransactionUseCase) GetTransactionIdsOfUser(ctx context.Context, user models.UserModel) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionIdsOfUser", ctx, user)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionIdsOfUser indicates an expected call of GetTransactionIdsOfUser.
func (mr *MockTransactionUseCaseMockRecorder) GetTransactionIdsOfUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionIdsOfUser", reflect.TypeOf((*MockTransactionUseCase)(nil).GetTransactionIdsOfUser), ctx, user)
}

// IsUserAuthorOfTransaction mocks base method.
func (m *MockTransactionUseCase) IsUserAuthorOfTransaction(user models.UserModel, transaction models.TransactionModel) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAuthorOfTransaction", user, transaction)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAuthorOfTransaction indicates an expected call of IsUserAuthorOfTransaction.
func (mr *MockTransactionUseCaseMockRecorder) IsUserAuthorOfTransaction(user, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAuthorOfTransaction", reflect.TypeOf((*MockTransactionUseCase)(nil).IsUserAuthorOfTransaction), user, transaction)
}

// Search mocks base method.
func (m *MockTransactionUseCase) Search(ctx context.Context, userId int, filters repository.TransactionFilters) ([]models.TransactionModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, userId, filters)
	ret0, _ := ret[0].([]models.TransactionModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockTransactionUseCaseMockRecorder) Search(ctx, userId, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockTransactionUseCase)(nil).Search), ctx, userId, filters)
}

// Update mocks base method.
func (m *MockTransactionUseCase) Update(ctx context.Context, transaction models.TransactionModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTransactionUseCaseMockRecorder) Update(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTransactionUseCase)(nil).Update), ctx, transaction)
}
