// Code generated by MockGen. DO NOT EDIT.
// Source: avatar_uploader.go
//
// Generated by this command:
//
//	mockgen -source=avatar_uploader.go -destination=mocks/mock_avatar_uploader.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvatarUploader is a mock of AvatarUploader interface.
type MockAvatarUploader struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarUploaderMockRecorder
	isgomock struct{}
}

// MockAvatarUploaderMockRecorder is the mock recorder for MockAvatarUploader.
type MockAvatarUploaderMockRecorder struct {
	mock *MockAvatarUploader
}

// NewMockAvatarUploader creates a new mock instance.
func NewMockAvatarUploader(ctrl *gomock.Controller) *MockAvatarUploader {
	mock := &MockAvatarUploader{ctrl: ctrl}
	mock.recorder = &MockAvatarUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarUploader) EXPECT() *MockAvatarUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockAvatarUploader) Upload(ctx context.Context, reader io.Reader, extension string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, reader, extension)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarUploaderMockRecorder) Upload(ctx, reader, extension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarUploader)(nil).Upload), ctx, reader, extension)
}
