// Code generated by MockGen. DO NOT EDIT.
// Source: enums.go
//
// Generated by this command:
//
//	mockgen -source=enums.go -destination=mocks/mock_enums.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnumsUseCase is a mock of EnumsUseCase interface.
type MockEnumsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEnumsUseCaseMockRecorder
	isgomock struct{}
}

// MockEnumsUseCaseMockRecorder is the mock recorder for MockEnumsUseCase.
type MockEnumsUseCaseMockRecorder struct {
	mock *MockEnumsUseCase
}

// NewMockEnumsUseCase creates a new mock instance.
func NewMockEnumsUseCase(ctrl *gomock.Controller) *MockEnumsUseCase {
	mock := &MockEnumsUseCase{ctrl: ctrl}
	mock.recorder = &MockEnumsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnumsUseCase) EXPECT() *MockEnumsUseCaseMockRecorder {
	return m.recorder
}

// GetCategoryTypes mocks base method.
func (m *MockEnumsUseCase) GetCategoryTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetCategoryTypes indicates an expected call of GetCategoryTypes.
func (mr *MockEnumsUseCaseMockRecorder) GetCategoryTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTypes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetCategoryTypes))
}

// GetCurrencyCodes mocks base method.
func (m *MockEnumsUseCase) GetCurrencyCodes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyCodes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetCurrencyCodes indicates an expected call of GetCurrencyCodes.
func (mr *MockEnumsUseCaseMockRecorder) GetCurrencyCodes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyCodes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetCurrencyCodes))
}

// GetTransactionTypes mocks base method.
func (m *MockEnumsUseCase) GetTransactionTypes() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionTypes")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetTransactionTypes indicates an expected call of GetTransactionTypes.
func (mr *MockEnumsUseCaseMockRecorder) GetTransactionTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionTypes", reflect.TypeOf((*MockEnumsUseCase)(nil).GetTransactionTypes))
}
