// Code generated by MockGen. DO NOT EDIT.
// Source: support.go
//
// Generated by this command:
//
//	mockgen -source=support.go -destination=mocks/support.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	web_helpers "github.com/go-park-mail-ru/2026_1_GPTeam/internal/web/web_helpers"
	gomock "go.uber.org/mock/gomock"
)

// MockSupportUseCase is a mock of SupportUseCase interface.
type MockSupportUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSupportUseCaseMockRecorder
	isgomock struct{}
}

// MockSupportUseCaseMockRecorder is the mock recorder for MockSupportUseCase.
type MockSupportUseCaseMockRecorder struct {
	mock *MockSupportUseCase
}

// NewMockSupportUseCase creates a new mock instance.
func NewMockSupportUseCase(ctrl *gomock.Controller) *MockSupportUseCase {
	mock := &MockSupportUseCase{ctrl: ctrl}
	mock.recorder = &MockSupportUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupportUseCase) EXPECT() *MockSupportUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSupportUseCase) Create(ctx context.Context, data web_helpers.SupportRequest, userId int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data, userId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSupportUseCaseMockRecorder) Create(ctx, data, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSupportUseCase)(nil).Create), ctx, data, userId)
}

// Delete mocks base method.
func (m *MockSupportUseCase) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSupportUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSupportUseCase)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockSupportUseCase) GetAll(ctx context.Context) ([]models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSupportUseCaseMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSupportUseCase)(nil).GetAll), ctx)
}

// GetAllByUser mocks base method.
func (m *MockSupportUseCase) GetAllByUser(ctx context.Context, userId int) ([]models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByUser", ctx, userId)
	ret0, _ := ret[0].([]models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByUser indicates an expected call of GetAllByUser.
func (mr *MockSupportUseCaseMockRecorder) GetAllByUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByUser", reflect.TypeOf((*MockSupportUseCase)(nil).GetAllByUser), ctx, userId)
}

// GetById mocks base method.
func (m *MockSupportUseCase) GetById(ctx context.Context, id int) (models.SupportModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(models.SupportModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockSupportUseCaseMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockSupportUseCase)(nil).GetById), ctx, id)
}

// Update mocks base method.
func (m *MockSupportUseCase) Update(ctx context.Context, id int, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSupportUseCaseMockRecorder) Update(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSupportUseCase)(nil).Update), ctx, id, status)
}
