// Code generated by MockGen. DO NOT EDIT.
// Source: .\voice_transaction.go
//
// Generated by this command:
//
//	mockgen -source .\voice_transaction.go -destination .\mocks\voice_transaction.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2026_1_GPTeam/internal/application/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAIConsultantClient is a mock of AIConsultantClient interface.
type MockAIConsultantClient struct {
	ctrl     *gomock.Controller
	recorder *MockAIConsultantClientMockRecorder
	isgomock struct{}
}

// MockAIConsultantClientMockRecorder is the mock recorder for MockAIConsultantClient.
type MockAIConsultantClientMockRecorder struct {
	mock *MockAIConsultantClient
}

// NewMockAIConsultantClient creates a new mock instance.
func NewMockAIConsultantClient(ctrl *gomock.Controller) *MockAIConsultantClient {
	mock := &MockAIConsultantClient{ctrl: ctrl}
	mock.recorder = &MockAIConsultantClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAIConsultantClient) EXPECT() *MockAIConsultantClientMockRecorder {
	return m.recorder
}

// ParseTransaction mocks base method.
func (m *MockAIConsultantClient) ParseTransaction(ctx context.Context, transcript string, types, categories, currencies []string) (*models.TransactionDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTransaction", ctx, transcript, types, categories, currencies)
	ret0, _ := ret[0].(*models.TransactionDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTransaction indicates an expected call of ParseTransaction.
func (mr *MockAIConsultantClientMockRecorder) ParseTransaction(ctx, transcript, types, categories, currencies any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTransaction", reflect.TypeOf((*MockAIConsultantClient)(nil).ParseTransaction), ctx, transcript, types, categories, currencies)
}

// Transcribe mocks base method.
func (m *MockAIConsultantClient) Transcribe(ctx context.Context, audioData []byte, filename string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe", ctx, audioData, filename)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockAIConsultantClientMockRecorder) Transcribe(ctx, audioData, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockAIConsultantClient)(nil).Transcribe), ctx, audioData, filename)
}

// MockVoiceTransactionUseCase is a mock of VoiceTransactionUseCase interface.
type MockVoiceTransactionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVoiceTransactionUseCaseMockRecorder
	isgomock struct{}
}

// MockVoiceTransactionUseCaseMockRecorder is the mock recorder for MockVoiceTransactionUseCase.
type MockVoiceTransactionUseCaseMockRecorder struct {
	mock *MockVoiceTransactionUseCase
}

// NewMockVoiceTransactionUseCase creates a new mock instance.
func NewMockVoiceTransactionUseCase(ctrl *gomock.Controller) *MockVoiceTransactionUseCase {
	mock := &MockVoiceTransactionUseCase{ctrl: ctrl}
	mock.recorder = &MockVoiceTransactionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoiceTransactionUseCase) EXPECT() *MockVoiceTransactionUseCaseMockRecorder {
	return m.recorder
}

// CreateVoiceTransaction mocks base method.
func (m *MockVoiceTransactionUseCase) CreateVoiceTransaction(ctx context.Context, audioData []byte, filename string) (*models.TransactionDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVoiceTransaction", ctx, audioData, filename)
	ret0, _ := ret[0].(*models.TransactionDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVoiceTransaction indicates an expected call of CreateVoiceTransaction.
func (mr *MockVoiceTransactionUseCaseMockRecorder) CreateVoiceTransaction(ctx, audioData, filename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVoiceTransaction", reflect.TypeOf((*MockVoiceTransactionUseCase)(nil).CreateVoiceTransaction), ctx, audioData, filename)
}
