on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Run tests
        run: go test ./...
      - name: Run coverage
        run: make test-cover-html
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests_coverage.html
          path: coverage.html

#  lint:
#    runs-on: ubuntu-latest
