on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Run tests
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: make test
      - name: Run coverage
        if: always()
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: make test-cover-html
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: tests_coverage_html_file
          path: coverage.html

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m --verbose
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
