on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Run tests
        run: make test
      - name: Run coverage
        if: always()
        run: make test-cover-html
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: tests_coverage_html_file
          path: coverage.html
      - name: Extract coverage percent
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      - name: Update README with coverage
        run: |
          sed -i "s/Coverage: .*%/Coverage: ${{ env.COVERAGE }}%/" README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update coverage badge [skip ci]" || exit 0
          git push

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m --verbose
      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
